---
title: "Assignment 2"
author: "Lokesh Bharule, 787425"
output: pdf_document
---

Loading of Libraries

```{r message = FALSE, warning = FALSE}
library(tidyverse)
library(ggplot2)
```

PLOT 1
```{r message=FALSE, warning=FALSE}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(size = 2) + 
  geom_smooth(method = 'loess', formula = y~x, size = 1.5, se = FALSE)
```

\newpage
PLOT 2
```{r message=FALSE, warning=FALSE}
ggplot(mpg, aes(x = displ, y = hwy, colours = drv)) +
  geom_point(size = 2) +
  geom_smooth(method = 'loess', formula = y~x, size = 1.5, se = FALSE)
```

\newpage
PLOT 3
```{r message=FALSE, warning=FALSE}
ggplot(mpg, aes(x = displ, y = hwy, colour = drv)) +
  geom_point() +
  geom_smooth(method = 'loess', formula = y~x, se = FALSE)
```

\newpage
PLOT 4
```{r message=FALSE, warning=FALSE}
ggplot(mpg, aes(x = displ, y = hwy, colour = drv)) +
  geom_point() +
  geom_smooth(aes(group = 1), method = 'loess', formula = y~x, se = FALSE)
```

\newpage
PLOT 5
```{r message=FALSE, warning=FALSE}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_point(aes(colour = drv)) +
  geom_smooth(aes(linetype=drv), method = 'loess', formula = y~x, se = FALSE, fullrange = TRUE, na.rm = TRUE)
```

\newpage
PLOT 6
```{r message=FALSE, warning=FALSE}
ggplot(mpg, aes(x = displ, y = hwy, fill = drv)) +
  geom_point(shape = 21, size = 3, colour = "white", stroke = 3)
```

